spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: USER
    password: PASSWORD

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: DEBUG