spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  logging:
    level:
      liquibase: DEBUG